### ISSUE TITLE
Cannot output some logs at destroying time

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/terasoluna-gfw-web-blank#452]
## Description

My application that based on the `terasoluna-gfw-web-blank` lost logs at destroying time.

## Possible Solution

I can resolved this issue by configured the `LogbackServletContextListener` manually on `web.xml` as follow:

```xml

    <!-- Start adding setting -->
    <listener>
        <listener-class>ch.qos.logback.classic.servlet.LogbackServletContextListener</listener-class>
    </listener>
    <context-param>
        <param-name>logbackDisableServletContainerInitializer</param-name>
        <param-value>true</param-value>
    </context-param>
    <!-- End adding setting -->

    <listener>
        <listener-class>org.springframework.web.context.ContextLoaderListener</listener-class>
    </listener>
    <!-- ... -->
```

**Points**

* Define the `LogbackServletContextListener` before the `ContextLoaderListener` (Probably, `LogbackServletContextListener` should be defined at first)
* Disable the feature that register `LogbackServletContextListener` automatically using context parameter

## Affect versions
- 5.6.0.RELEASE

## Fix repositories
> Repositories to fix with this issue.

- [x] terasoluna-gfw-web-blank
- [x] m-j
- [x] m-t

## Issue links

- http://logback.qos.ch/manual/configuration.html#stopContext
- https://stackoverflow.com/questions/47184045/spring-predestroy-no-logging-because-logback-stops-too-soon

**Comment by yoshikawaa** [comment]
@kazuki43zoo Thanks for your report & suggestion.

One thing I'm curious about is that whether or not this happens depends on the environment.

LogbackServletContextListener is performed by LogbackServletContainerInitializer, but since ServletContainerInitializer is detected by the service provider lookup mechanism of the execution environment, it is possible that the order in which listeners are registered may change depending on the environment.

https://javaee.github.io/javaee-spec/javadocs/javax/servlet/ServletContainerInitializer.html
> Implementations of this interface must be declared by a JAR file resource located inside the META-INF/services directory and named for the fully qualified class name of this interface, and will be discovered using the runtime's service provider lookup mechanism or a container specific mechanism that is semantically equivalent to it. In either case, ServletContainerInitializer services from web fragment JAR files excluded from an absolute ordering must be ignored, and the order in which these services are discovered must follow the application's classloading delegation model.

-----

In addition, although it was possible to output the destroy log by disabling the mechanism that detects this ServletContainerInitializer, there may be unintended side effects.

```xml
<web-app ...
    metadata-complete="true">

    <absolute-ordering />

    <listener>
        <listener-class>ch.qos.logback.classic.servlet.LogbackServletContextListener</listener-class>
    </listener>

```

Add `web-app#metadata-complete="true"` & `absolute-ordering`.
(Add initializers that you do not want to disable in `absolute-ordering`.)

**Comment by kazuki43zoo** [comment]
> One thing I'm curious about is that whether or not this happens depends on the environment.

My understanding, I think this behavior will be happen on all application servers regardless a class loader implementation because listener that defined on `web.xml` will register to the `ServletContext` at first.

**Comment by kazuki43zoo** [comment]
> In addition, although it was possible to output the destroy log by disabling the mechanism that detects this ServletContainerInitializer, there may be unintended side effects.

I want to avoid this solution because maybe there are side effects.

**Comment by yoshikawaa** [comment]
For team members.

##### TODO
- [ ] Make sure there are no logs during destroy in each test environment.
- [ ] Verify that logging is output and unexpected errors do not occur with the setting of possible solution.

##### SOLUTION POLICY
If the problem occurs in all test environments?
* YES: Change the blank project settings.
* NO: Introduce settings in guidelines.

**Comment by btootomoyuk** [comment]
We have tried to reproduce the event in the following environments, and we have confirmed that the log is output on destroy without any modification in our environment.
- tomcat9 / openjdk8
- tomcat9 / openjdk11
- jboss7 / openjdk11
- weblogic12c / oraclejdk8

@kazuki43zoo 
If you don't mind, could you please tell us the environment in which you were running the application?

**Comment by yoshikawaa** [comment]
@btootomoyuk 
You can see that some of the logs that are output when you quit the application with default setting are missing.

### Base setting

* logback.xml

```xml
    <!-- 3rdparty Loggers -->
    <logger name="org.springframework">
        <level value="trace" />
    </logger>

    <logger name="org.springframework.web.servlet">
        <level value="trace" />
    </logger>
```

### Logs when default setting

```console
2 01, 2021 10:35:12 午前 org.apache.catalina.startup.Catalina start
情報: Server startup in 27335 ms
date:2021-02-01 10:35:14	thread:RMI TCP Connection(4)-127.0.0.1	X-Track:	level:DEBUG	logger:o.s.web.context.support.XmlWebApplicationContext	message:Closing WebApplicationContext for namespace 'appServlet-servlet', started on Mon Feb 01 10:34:59 JST 2021, parent: Root WebApplicationContext
date:2021-02-01 10:35:14	thread:RMI TCP Connection(4)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.b.factory.support.DefaultListableBeanFactory	message:Returning cached instance of singleton bean 'lifecycleProcessor'
date:2021-02-01 10:35:14	thread:RMI TCP Connection(4)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.b.factory.support.DefaultListableBeanFactory	message:Destroying singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@88edd90: defining beans [org.springframework.context.support.PropertySourcesPlaceholderConfigurer#0,mvcContentNegotiationManager,org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping,mvcCorsConfigurations,org.springframework.format.support.FormattingConversionServiceFactoryBean#0,org.springframework.validation.beanvalidation.OptionalValidatorFactoryBean#0,org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter,mvcUriComponentsContributor,org.springframework.web.servlet.handler.MappedInterceptor#0,org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver#0,org.springframework.web.servlet.mvc.annotation.ResponseStatusExceptionResolver#0,org.springframework.web.servlet.mvc.support.DefaultHandlerExceptionResolver#0,org.springframework.web.servlet.handler.BeanNameUrlHandlerMapping,org.springframework.web.servlet.mvc.HttpRequestHandlerAdapter,org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter,mvcHandlerMappingIntrospector,org.springframework.web.servlet.resource.DefaultServletHttpRequestHandler#0,org.springframework.web.servlet.handler.SimpleUrlHandlerMapping#0,helloController,org.springframework.context.annotation.internalConfigurationAnnotationProcessor,org.springframework.context.annotation.internalAutowiredAnnotationProcessor,org.springframework.context.annotation.internalCommonAnnotationProcessor,org.springframework.context.event.internalEventListenerProcessor,org.springframework.context.event.internalEventListenerFactory,mvcResourceUrlProvider,org.springframework.web.servlet.handler.MappedInterceptor#1,mvcPathMatcher,mvcUrlPathHelper,org.springframework.web.servlet.resource.ResourceHttpRequestHandler#0,org.springframework.web.servlet.handler.SimpleUrlHandlerMapping#1,org.springframework.web.servlet.handler.MappedInterceptor#2,org.springframework.web.servlet.handler.MappedInterceptor#3,org.springframework.web.servlet.handler.MappedInterceptor#4,mvcViewResolver,requestDataValueProcessor,systemExceptionResolver,handlerExceptionResolverLoggingInterceptor,org.springframework.aop.config.internalAutoProxyCreator,org.springframework.aop.support.DefaultBeanFactoryPointcutAdvisor#0]; parent: org.springframework.beans.factory.support.DefaultListableBeanFactory@5b933786
date:2021-02-01 10:35:14	thread:RMI TCP Connection(4)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.b.factory.support.DefaultListableBeanFactory	message:Retrieved dependent beans for bean 'util:list#51fcecaa': [requestDataValueProcessor]
date:2021-02-01 10:35:14	thread:RMI TCP Connection(4)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.b.factory.support.DefaultListableBeanFactory	message:Retrieved dependent beans for bean 'org.springframework.security.web.servlet.support.csrf.CsrfRequestDataValueProcessor#9a38c90': [util:list#51fcecaa]
date:2021-02-01 10:35:14	thread:RMI TCP Connection(4)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.beans.factory.support.DisposableBeanAdapter 	message:Invoking destroy() on bean with name 'util:list#51fcecaa'
date:2021-02-01 10:35:14	thread:RMI TCP Connection(4)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.b.factory.support.DefaultListableBeanFactory	message:Retrieved dependent beans for bean 'org.springframework.validation.beanvalidation.OptionalValidatorFactoryBean#0': [(inner bean)#19a5d711, (inner bean)#19a5d711#1]
date:2021-02-01 10:35:14	thread:RMI TCP Connection(4)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.b.factory.support.DefaultListableBeanFactory	message:Retrieved dependent beans for bean '(inner bean)#19a5d711': [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter]
date:2021-02-01 10:35:14	thread:RMI TCP Connection(4)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.b.factory.support.DefaultListableBeanFactory	message:Retrieved dependent beans for bean '(inner bean)#15cf663c': [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter]
date:2021-02-01 10:35:14	thread:RMI TCP Connection(4)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.b.factory.support.DefaultListableBeanFactory	message:Retrieved dependent beans for bean '(inner bean)#6fe37577': [(inner bean)#3565ee15]
date:2021-02-01 10:35:14	thread:RMI TCP Connection(4)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.b.factory.support.DefaultListableBeanFactory	message:Retrieved dependent beans for bean '(inner bean)#19a5d711#1': [(inner bean)#4e0d2ddd]
date:2021-02-01 10:35:14	thread:RMI TCP Connection(4)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.b.factory.support.DefaultListableBeanFactory	message:Retrieved dependent beans for bean '(inner bean)#4e0d2ddd': [mvcUriComponentsContributor]
date:2021-02-01 10:35:14	thread:RMI TCP Connection(4)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.b.factory.support.DefaultListableBeanFactory	message:Retrieved dependent beans for bean '(inner bean)#15cf663c#1': [(inner bean)#4e0d2ddd]
date:2021-02-01 10:35:14	thread:RMI TCP Connection(4)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.b.factory.support.DefaultListableBeanFactory	message:Retrieved dependent beans for bean '(inner bean)#6fe37577#1': [(inner bean)#3565ee15#1]
date:2021-02-01 10:35:14	thread:RMI TCP Connection(4)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.beans.factory.support.DisposableBeanAdapter 	message:Invoking destroy() on bean with name 'org.springframework.validation.beanvalidation.OptionalValidatorFactoryBean#0'
date:2021-02-01 10:35:14	thread:RMI TCP Connection(4)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.b.factory.support.DefaultListableBeanFactory	message:Retrieved dependent beans for bean '(inner bean)#7d0bca3d': [(inner bean)#781ce680]
date:2021-02-01 10:35:14	thread:RMI TCP Connection(4)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.b.factory.support.DefaultListableBeanFactory	message:Retrieved dependent beans for bean '(inner bean)#781ce680': [org.springframework.web.servlet.handler.MappedInterceptor#1]
```

### Logs when possible Solution setting

* web.xml

```xml
    <!-- Start adding setting -->
    <listener>
        <listener-class>ch.qos.logback.classic.servlet.LogbackServletContextListener</listener-class>
    </listener>
    <context-param>
        <param-name>logbackDisableServletContainerInitializer</param-name>
        <param-value>true</param-value>
    </context-param>
    <!-- End adding setting -->

    <listener>
        <listener-class>org.springframework.web.context.ContextLoaderListener</listener-class>
    </listener>
```

```console
2 01, 2021 10:33:10 午前 org.apache.catalina.startup.Catalina start
情報: Server startup in 27819 ms
date:2021-02-01 10:33:19	thread:RMI TCP Connection(3)-127.0.0.1	X-Track:	level:DEBUG	logger:o.s.web.context.support.XmlWebApplicationContext	message:Closing WebApplicationContext for namespace 'appServlet-servlet', started on Mon Feb 01 10:32:56 JST 2021, parent: Root WebApplicationContext
date:2021-02-01 10:33:19	thread:RMI TCP Connection(3)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.b.factory.support.DefaultListableBeanFactory	message:Returning cached instance of singleton bean 'lifecycleProcessor'
date:2021-02-01 10:33:19	thread:RMI TCP Connection(3)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.b.factory.support.DefaultListableBeanFactory	message:Destroying singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@373743f: defining beans [org.springframework.context.support.PropertySourcesPlaceholderConfigurer#0,mvcContentNegotiationManager,org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping,mvcCorsConfigurations,org.springframework.format.support.FormattingConversionServiceFactoryBean#0,org.springframework.validation.beanvalidation.OptionalValidatorFactoryBean#0,org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter,mvcUriComponentsContributor,org.springframework.web.servlet.handler.MappedInterceptor#0,org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver#0,org.springframework.web.servlet.mvc.annotation.ResponseStatusExceptionResolver#0,org.springframework.web.servlet.mvc.support.DefaultHandlerExceptionResolver#0,org.springframework.web.servlet.handler.BeanNameUrlHandlerMapping,org.springframework.web.servlet.mvc.HttpRequestHandlerAdapter,org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter,mvcHandlerMappingIntrospector,org.springframework.web.servlet.resource.DefaultServletHttpRequestHandler#0,org.springframework.web.servlet.handler.SimpleUrlHandlerMapping#0,helloController,org.springframework.context.annotation.internalConfigurationAnnotationProcessor,org.springframework.context.annotation.internalAutowiredAnnotationProcessor,org.springframework.context.annotation.internalCommonAnnotationProcessor,org.springframework.context.event.internalEventListenerProcessor,org.springframework.context.event.internalEventListenerFactory,mvcResourceUrlProvider,org.springframework.web.servlet.handler.MappedInterceptor#1,mvcPathMatcher,mvcUrlPathHelper,org.springframework.web.servlet.resource.ResourceHttpRequestHandler#0,org.springframework.web.servlet.handler.SimpleUrlHandlerMapping#1,org.springframework.web.servlet.handler.MappedInterceptor#2,org.springframework.web.servlet.handler.MappedInterceptor#3,org.springframework.web.servlet.handler.MappedInterceptor#4,mvcViewResolver,requestDataValueProcessor,systemExceptionResolver,handlerExceptionResolverLoggingInterceptor,org.springframework.aop.config.internalAutoProxyCreator,org.springframework.aop.support.DefaultBeanFactoryPointcutAdvisor#0]; parent: org.springframework.beans.factory.support.DefaultListableBeanFactory@5eeb7b5b
date:2021-02-01 10:33:19	thread:RMI TCP Connection(3)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.b.factory.support.DefaultListableBeanFactory	message:Retrieved dependent beans for bean 'util:list#59ea8f1b': [requestDataValueProcessor]
date:2021-02-01 10:33:19	thread:RMI TCP Connection(3)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.b.factory.support.DefaultListableBeanFactory	message:Retrieved dependent beans for bean 'org.springframework.security.web.servlet.support.csrf.CsrfRequestDataValueProcessor#630ae6ce': [util:list#59ea8f1b]
date:2021-02-01 10:33:19	thread:RMI TCP Connection(3)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.beans.factory.support.DisposableBeanAdapter 	message:Invoking destroy() on bean with name 'util:list#59ea8f1b'
date:2021-02-01 10:33:19	thread:RMI TCP Connection(3)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.b.factory.support.DefaultListableBeanFactory	message:Retrieved dependent beans for bean 'org.springframework.validation.beanvalidation.OptionalValidatorFactoryBean#0': [(inner bean)#7b787996, (inner bean)#7b787996#1]
date:2021-02-01 10:33:19	thread:RMI TCP Connection(3)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.b.factory.support.DefaultListableBeanFactory	message:Retrieved dependent beans for bean '(inner bean)#7b787996': [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter]
date:2021-02-01 10:33:19	thread:RMI TCP Connection(3)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.b.factory.support.DefaultListableBeanFactory	message:Retrieved dependent beans for bean '(inner bean)#26505df2': [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter]
date:2021-02-01 10:33:19	thread:RMI TCP Connection(3)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.b.factory.support.DefaultListableBeanFactory	message:Retrieved dependent beans for bean '(inner bean)#4089505c': [(inner bean)#59bcab83]
date:2021-02-01 10:33:19	thread:RMI TCP Connection(3)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.b.factory.support.DefaultListableBeanFactory	message:Retrieved dependent beans for bean '(inner bean)#7b787996#1': [(inner bean)#16d8a25e]
date:2021-02-01 10:33:19	thread:RMI TCP Connection(3)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.b.factory.support.DefaultListableBeanFactory	message:Retrieved dependent beans for bean '(inner bean)#16d8a25e': [mvcUriComponentsContributor]
date:2021-02-01 10:33:19	thread:RMI TCP Connection(3)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.b.factory.support.DefaultListableBeanFactory	message:Retrieved dependent beans for bean '(inner bean)#26505df2#1': [(inner bean)#16d8a25e]
date:2021-02-01 10:33:19	thread:RMI TCP Connection(3)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.b.factory.support.DefaultListableBeanFactory	message:Retrieved dependent beans for bean '(inner bean)#4089505c#1': [(inner bean)#59bcab83#1]
date:2021-02-01 10:33:19	thread:RMI TCP Connection(3)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.beans.factory.support.DisposableBeanAdapter 	message:Invoking destroy() on bean with name 'org.springframework.validation.beanvalidation.OptionalValidatorFactoryBean#0'
date:2021-02-01 10:33:19	thread:RMI TCP Connection(3)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.b.factory.support.DefaultListableBeanFactory	message:Retrieved dependent beans for bean '(inner bean)#4cd78959': [(inner bean)#583c416c]
date:2021-02-01 10:33:19	thread:RMI TCP Connection(3)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.b.factory.support.DefaultListableBeanFactory	message:Retrieved dependent beans for bean '(inner bean)#583c416c': [org.springframework.web.servlet.handler.MappedInterceptor#1]
date:2021-02-01 10:33:19	thread:RMI TCP Connection(3)-127.0.0.1	X-Track:	level:DEBUG	logger:o.s.web.context.support.XmlWebApplicationContext	message:Closing Root WebApplicationContext, started on Mon Feb 01 10:32:53 JST 2021
date:2021-02-01 10:33:19	thread:RMI TCP Connection(3)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.b.factory.support.DefaultListableBeanFactory	message:Returning cached instance of singleton bean 'lifecycleProcessor'
date:2021-02-01 10:33:19	thread:RMI TCP Connection(3)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.b.factory.support.DefaultListableBeanFactory	message:Destroying singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@5eeb7b5b: defining beans [org.springframework.context.annotation.internalConfigurationAnnotationProcessor,org.springframework.context.annotation.internalAutowiredAnnotationProcessor,org.springframework.context.annotation.internalCommonAnnotationProcessor,org.springframework.context.event.internalEventListenerProcessor,org.springframework.context.event.internalEventListenerFactory,resultMessagesLoggingInterceptor,org.springframework.aop.config.internalAutoProxyCreator,org.springframework.aop.support.DefaultBeanFactoryPointcutAdvisor#0,passwordEncoder,org.springframework.context.support.PropertySourcesPlaceholderConfigurer#0,beanMapper,messageSource,exceptionCodeResolver,exceptionLogger,exceptionLoggingFilter,org.springframework.security.filterChains,org.springframework.security.filterChainProxy,org.springframework.security.web.DefaultSecurityFilterChain#0,org.springframework.security.web.PortMapperImpl#0,org.springframework.security.web.PortResolverImpl#0,org.springframework.security.config.authentication.AuthenticationManagerFactoryBean#0,org.springframework.security.authentication.ProviderManager#0,requestDataValueProcessor,org.springframework.security.web.csrf.LazyCsrfTokenRepository#0,org.springframework.security.web.context.HttpSessionSecurityContextRepository#0,org.springframework.security.web.authentication.session.CompositeSessionAuthenticationStrategy#0,org.springframework.security.web.savedrequest.HttpSessionRequestCache#0,org.springframework.security.config.http.HttpConfigurationBuilder$SecurityContextHolderAwareRequestFilterBeanFactory#0,org.springframework.security.config.http.FilterInvocationSecurityMetadataSourceParser$DefaultWebSecurityExpressionHandlerBeanFactory#0,org.springframework.security.config.http.FilterInvocationSecurityMetadataSourceParser$DefaultWebSecurityExpressionHandlerBeanFactory#0$created#0,org.springframework.security.access.vote.AffirmativeBased#0,org.springframework.security.web.access.intercept.FilterSecurityInterceptor#0,org.springframework.security.web.access.DefaultWebInvocationPrivilegeEvaluator#0,org.springframework.security.authentication.AnonymousAuthenticationProvider#0,org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter#0,org.springframework.security.userDetailsServiceFactory,org.springframework.security.web.DefaultSecurityFilterChain#1,org.springframework.security.authentication.DefaultAuthenticationEventPublisher#0,org.springframework.security.authenticationManager,accessDeniedHandler,userIdMDCPutFilter]; root of factory hierarchy
date:2021-02-01 10:33:19	thread:RMI TCP Connection(3)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.beans.factory.support.DisposableBeanAdapter 	message:Invoking destroy() on bean with name 'org.springframework.security.filterChainProxy'
date:2021-02-01 10:33:19	thread:RMI TCP Connection(3)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.b.factory.support.DefaultListableBeanFactory	message:Retrieved dependent beans for bean '(inner bean)#7cfe97db': [org.springframework.security.filterChainProxy]
date:2021-02-01 10:33:19	thread:RMI TCP Connection(3)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.beans.factory.support.DisposableBeanAdapter 	message:Invoking destroy() on bean with name 'org.springframework.security.filterChains'
date:2021-02-01 10:33:19	thread:RMI TCP Connection(3)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.b.factory.support.DefaultListableBeanFactory	message:Retrieved dependent beans for bean '(inner bean)#16d9c898': [org.springframework.security.web.DefaultSecurityFilterChain#1]
date:2021-02-01 10:33:19	thread:RMI TCP Connection(3)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.b.factory.support.DefaultListableBeanFactory	message:Retrieved dependent beans for bean '(inner bean)#6f9de548': [org.springframework.security.web.DefaultSecurityFilterChain#1]
date:2021-02-01 10:33:19	thread:RMI TCP Connection(3)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.beans.factory.support.DisposableBeanAdapter 	message:Invoking destroy() on bean with name '(inner bean)#5fada492'
date:2021-02-01 10:33:19	thread:RMI TCP Connection(3)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.beans.factory.support.DisposableBeanAdapter 	message:Invoking destroy() on bean with name '(inner bean)#410308ff'
date:2021-02-01 10:33:19	thread:RMI TCP Connection(3)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.beans.factory.support.DisposableBeanAdapter 	message:Invoking destroy() on bean with name '(inner bean)#787345aa'
date:2021-02-01 10:33:19	thread:RMI TCP Connection(3)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.b.factory.support.DefaultListableBeanFactory	message:Retrieved dependent beans for bean '(inner bean)#3e71b1a4': [(inner bean)#787345aa]
date:2021-02-01 10:33:19	thread:RMI TCP Connection(3)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.beans.factory.support.DisposableBeanAdapter 	message:Invoking destroy() on bean with name '(inner bean)#7ca0b2cf'
date:2021-02-01 10:33:19	thread:RMI TCP Connection(3)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.beans.factory.support.DisposableBeanAdapter 	message:Invoking destroy() on bean with name '(inner bean)#1c078424'
date:2021-02-01 10:33:19	thread:RMI TCP Connection(3)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.b.factory.support.DefaultListableBeanFactory	message:Retrieved dependent beans for bean '(inner bean)#54ba7366': [(inner bean)#1c078424]
date:2021-02-01 10:33:19	thread:RMI TCP Connection(3)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.beans.factory.support.DisposableBeanAdapter 	message:Invoking destroy() on bean with name '(inner bean)#149a793a'
date:2021-02-01 10:33:19	thread:RMI TCP Connection(3)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.beans.factory.support.DisposableBeanAdapter 	message:Invoking destroy() on bean with name '(inner bean)#50e3019b'
date:2021-02-01 10:33:19	thread:RMI TCP Connection(3)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.beans.factory.support.DisposableBeanAdapter 	message:Invoking destroy() on bean with name '(inner bean)#2c143041'
date:2021-02-01 10:33:19	thread:RMI TCP Connection(3)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.beans.factory.support.DisposableBeanAdapter 	message:Invoking destroy() on bean with name '(inner bean)#1635b03f'
date:2021-02-01 10:33:19	thread:RMI TCP Connection(3)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.b.factory.support.DefaultListableBeanFactory	message:Retrieved dependent beans for bean '(inner bean)#54ba7366#1': [(inner bean)#1635b03f]
date:2021-02-01 10:33:19	thread:RMI TCP Connection(3)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.beans.factory.support.DisposableBeanAdapter 	message:Invoking destroy() on bean with name '(inner bean)#2f57fc23'
date:2021-02-01 10:33:19	thread:RMI TCP Connection(3)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.beans.factory.support.DisposableBeanAdapter 	message:Invoking destroy() on bean with name '(inner bean)#35188cd2'
date:2021-02-01 10:33:19	thread:RMI TCP Connection(3)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.b.factory.support.DefaultListableBeanFactory	message:Retrieved dependent beans for bean '(inner bean)#4d548ae7': [(inner bean)#35188cd2]
date:2021-02-01 10:33:19	thread:RMI TCP Connection(3)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.b.factory.support.DefaultListableBeanFactory	message:Retrieved dependent beans for bean '(inner bean)#66d1cdea#1': [(inner bean)#16d9c898]
date:2021-02-01 10:33:19	thread:RMI TCP Connection(3)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.beans.factory.support.DisposableBeanAdapter 	message:Invoking destroy() on bean with name '(inner bean)#16d9c898'
date:2021-02-01 10:33:19	thread:RMI TCP Connection(3)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.beans.factory.support.DisposableBeanAdapter 	message:Invoking destroy() on bean with name 'userIdMDCPutFilter'
date:2021-02-01 10:33:19	thread:RMI TCP Connection(3)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.beans.factory.support.DisposableBeanAdapter 	message:Invoking destroy() on bean with name 'org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter#0'
date:2021-02-01 10:33:19	thread:RMI TCP Connection(3)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.b.factory.support.DefaultListableBeanFactory	message:Retrieved dependent beans for bean '(inner bean)#13572152': [org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter#0]
date:2021-02-01 10:33:19	thread:RMI TCP Connection(3)-127.0.0.1	X-Track:	level:TRACE	logger:o.s.beans.factory.support.DisposableBeanAdapter 	message:Invoking destroy() on bean with name 'exceptionLoggingFilter'
```

**Comment by btkatoufm** [comment]
@kazuki43zoo Thanks for your report.

It will be closed because it corresponds to this ISSUE.
