### ISSUE TITLE
Apply Spring 4 & IO Platform

### ISSUE THREAD

**Issue by btshimizukza** [terasolunaorg/terasoluna-gfw-web-blank#48]
see terasolunaorg/terasoluna-gfw#132 & terasolunaorg/terasoluna-gfw#178.

- [x] Modify pom file. #52
- [x] Apply Commons-dbcp2. #54 
- [x] Add el-api for test. Feedback from guideline of Validation(detail see [here](https://github.com/terasolunaorg/guideline/pull/603/files)) #55 
- [x] Add dependency for test. #55 
- [x] Apply namespace of ViewResolve #56
